config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "boards#index"



 resources :boards do 
  resources :lists
 end
 resources :lists do
   resources :tasks
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :lists, dependent: :destroy
  

  def self.all_boards(user_id)
    Board.find_by_sql(
      "SELECT *
      FROM boards AS b
      WHERE b.user_id = #{user_id}"
    )
  end

  def self.single_board(board_id, user_id)
    Board.find_by_sql(["
      SELECT *
      FROM boards AS b
      WHERE b.id = ? AND b.user_id = ?
      ", board_id, user_id]).first
  end

   def self.create_board(p, user_id)
    Board.find_by_sql(["
      INSERT INTO boards (name, image, user_id, created_at, updated_at)
      VALUES (:name, :image, :user_id, :created_at, :updated_at);
      ", {
        name: p[:name],
        image: p[:image],
        user_id: user_id,
        created_at: DateTime.now,
        updated_at: DateTime.now
      }])
    end

    def self.update_board(board_id, p)
      Board.find_by_sql(["
        UPDATE boards AS b
        SET name = ?, image = ?, start_date = ?, finish_date = ?, updated_at = ?
        WHERE b.id = ?
        ;", p[:name], p[:image], p[:start_date], p[:finish_date], DateTime.now, board_id])
    end

      def self.delete_board(board_id)
        Board.find_by_sql(["
          DELETE FROM boards AS b
          WHERE b.id = ?;", board_id])
      end

  end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :boards
  has_many :tasks
  end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
  
end

app/models/user.rb
class User < ApplicationRecord
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :boards
  has_many :lists, through: :boards
  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [ :show, :edit, :update, :destroy]

  def index
    # must write a sql var in models  all_boards
    @boards = Board.all_boards(current_user.id)
  end

  def new
    @board = current_user.boards.new
  end

  def show
  end

  def create
  # INSERT one record write sql board model
    Board.create_board(board_params, current_user.id)
    redirect_to boards_path
  end

  def edit
  end

  def update
    Board.update_board(@board.id, board_params)
    redirect_to boards_path
  end

  def destroy
    Board.delete_board(@board.id)
    redirect_to boards_path
  end

  private

  def set_board
    #must write a method single board in board model w/sql
    @board = Board.single_board(current_user.id, params[:id])
  end
  def board_params
    params.require(:board). permit(:name, :image, :start_date, :finish_date)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_board
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  
  def index
    @lists = @board.lists
  end

  def new
    @list = @board.lists.new
    
  end

  def create
   @list = @board.lists.new(list_params)
   if @list.save 
    redirect_to [@board, @list]
   else
    render :new
   end
  end

  def show

  end
  def update
    if @list.update(list_params)
      redirect_to [@board, @list]
    else
      render :edit
    end
  end

  def edit

  end

  def destroy
  @list.destroy
  redirect_to board_lists_path(board)
  end

  private
  def set_board
    @board = Board.find(params[:board_id])
  end

  def set_list
    @list = List.find(params[:id])
  end
  
  def list_params
    params.require(:list).permit(:name, :priority)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_list
  before_action :set_task, only: [:show, :edit, :destroy, :update]
  def new
    @task = Task.new
  end

  def create
    @task = @list.tasks.new(task_params)
    if @task.save
      redirect_to board_list_path(@list.board_id, @list)
    else
      render :new
    end
  end

  def update
    if @task.update(list_params)
      redirect_to board_list_path(@list.board_id, @task)
    else
      render :edit
    end
  end

  def show
  end

  def edit
  end

  def destroy
  @task.destroy
  redirect_to board_lists_path
  end
  
  private
  def set_list
    @list = List.find(params[:list_id])
    end

  def set_task
    @task = Task.find(params[:id])
  end

   def task_params
    params.require(:task).permit(:name, :completed, :priority)
   end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/boards/_form.html.erb
<%= form_with(model: @board, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "input" %>
  </div>
 
 <div class="field">
   <%= f.label :start_date %>
   <%= f.text_field :start_date, class: "input" %>
 </div>
 <div class="field">
   <%= f.label :finish_date %>
   <%= f.text_field :finish_date, class: "input" %>
 </div>
 <%= f.submit nil, class: "ui blue button" %>
<% end %>

app/views/boards/edit.html.erb
<h1>Edit Your Board</h1>
<%= render 'form'%>

app/views/boards/index.html.erb
<h1 class="ui header"><%= current_user.full_name %> Boards</h1>
<%= link_to 'New Board', new_board_path %>
<div class="ui divider"></div>

<div class="ui grid">
  <% @boards.each do |board| %>
    <div class="sixteen wide mobile eight wide tablet four wide computer column">
      <div class="ui card">
        <div class="image">
          <img src="https://picsum.photos/200/<%= board.image %>?random=1" />
        </div>
        <div class="content">
          <%= link_to "#{board.name}", board, class: "header" %>
        </div>
        <div class="extra content">
          <div class="ui two buttons">
            <div class="ui basic green button">
              <%= link_to 'Edit', edit_board_path(board) %>
            </div>
            <div class="ui basic red button">
              <%= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/boards/new.html.erb
<h1>Start New Board</h1>
<%= render 'form' %>

app/views/boards/show.html.erb
<h1 class="ui centered header"><%= " #{current_user.full_name} #{@board.name}" %></h1>
<div class="ui centered card">
  <div class="image">
     <img src="https://picsum.photos/200/<%= @board.image %>?random=2"/>
    </div>
    <div class="content">
      <p class=" centered header">
      <%= @board.name %> 
    </p>
</div>
</div>

<div class="ui divider"></div>

<h2><%= @board.lists.length <= 0 ? "No lists" : "" %></h2> 
<div class="ui card">
  <div class="content">
  <% @board.lists.each do |list| %>
    <p class="header">
    <%= list.name %>
    </p>
  </div>
  <% end %>

  

    


  <div class="extra content">
    <%= link_to 'Edit', edit_board_path(@board) %> |
    <%= link_to 'Back', boards_path %> |
    <%= link_to 'View Lists', board_lists_path(@board) %>
  </div>
</div>


 

  

app/views/layouts/_navbar.html.erb
<nav class="ui menu">
  <%= link_to "Boards", boards_path, class: "item" %>
  <%= link_to "Add Board", new_board_path, class: "item" %>
  <div class="right menu">
    <% if current_user %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "item" %>
    <% else %>
      <%= link_to "Register", new_user_registration_path, class: "item" %>
      <%= link_to "Login", new_user_session_path, class: "item" %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskBoards</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <%= render "layouts/navbar" %>
  <div class="ui container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<h1><%= @list.id ? 'Edit list' : 'Create list' %></h1>
<hr/>
<%= form_with(model: [@board, @list], local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "input", placeholder: "To do List" %>
  </div>
 
 <div class="field">
   <%= f.label :priority %>
   <%= f.text_field :priority, class: "input", placeholder: "Priority Level 1-10"%>
 </div>
 
 <%= f.submit nil, class: "ui blue button" %>
<% end %>

app/views/lists/edit.html.erb
<h1>Need to Edit your Lists?</h1>

<%= render 'form' %>

<%= link_to "Back Up", lists_path, class: "ui right floated button"%>

app/views/lists/index.html.erb
<div class="header">Your Project Lists</div>
<div class="ui divider"></div>

<%= link_to 'Add List', new_board_list_path(@board) %>
<hr />
<h2><%= @lists.length <= 0 ? "No lists" : "" %></h2> 
  <div class="ui card">
  <% @lists.each do |list| %>
  <div class="content">
    <i class="right floated star icon"></i>
    <div class="header"><%= "#{list.name}"%></div>
    <div class="description">
      <div> <%= %> </div>
    </div>
  </div>
  <div class="ui bottom attached ">
   <div class="ui button"><%= link_to 'Delete', list, method: :delete %></div>
   <div class="ui button"><%= link_to 'Edit', edit_board_list_path(list) %></div>
  </div>
  <% end %>
</div>

    
 

app/views/lists/new.html.erb
<%= render 'form' %>

<div class='ui right floated button'><%= link_to 'Back', board_path(:board_id)%>

app/views/lists/show.html.erb
<h1>Project Lists</h1>
<hr/>

<div class="ui card">
  <div class="content">
    <i class="right floated star icon"></i>
    <div class="header"></div>
    <div class="description">
      <p><%= @list.name %></p>
      <p> Priority Level: <%= @list.priority %></p>
    </div>
  </div>
  <div class="ui bottom attached ">
   <div class="ui button"><%= link_to 'Delete', @list, method: :delete %></div>
   <div class="ui button"><%= link_to 'Edit', edit_list_path(@list) %></div>
   <div class="ui button"><%= link_to 'Add Task', new_list_task_path(@list) %></div>
  </div>
</div>
<h2>Tasks</h2>
<% @list.tasks.each do |x| %>
  <%= render 'tasks/task', { task: x } %>
<% end %>
<br />
<%= link_to 'Add Task', new_list_task_path(@list), class: "ui button blue" %>
<br />

app/views/tasks/_form.html.erb
<hr />
<p>Author: <%= task.name %></p>
<p><strong><%= task.body %></strong></p>
<hr/>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>

app/views/tasks/index.html.erb
<div class="header">Tasks To Complete List</div>
<div class="ui divider"></div>

<%= link_to 'Add Task', new_list_task_path(@list) %>
<hr />
<h2><%= @tasks.length <= 0 ? "No tasks" : "" %></h2> 
  <div class="ui card">
  <% @tasks.each do |task| %>
  <div class="content">
    <i class="right floated star icon"></i>
    <div class="header"><%= "#{@task.name}"%></div>
    <div class="description">
      <div> <%= %> </div>
    </div>
  </div>
  <div class="ui bottom attached ">
   <div class="ui button"><%= link_to 'Delete', task, method: :delete %></div>
   <div class="ui button"><%= link_to 'Edit', edit_list_task_path(@list, task) %></div>
  </div>
  <% end %>
</div>

app/views/tasks/new.html.erb
<h1>Add Task To List</h1>

<%= render 'form' %>

<div class='ui right floated button'><%= link_to 'Back', list_tasks_path(:list_id) %>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>